CREATE TABLE Osoba (ID int(10) NOT NULL AUTO_INCREMENT, RoleID int(10) NOT NULL, Imie varchar(255) NOT NULL, Nazwisko varchar(255) NOT NULL, Pesel varchar(255) NOT NULL, Email varchar(255) NOT NULL, Nr_tel varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Konsument (IdKonsumenta int(10) NOT NULL UNIQUE, OsobaID int(10) NOT NULL UNIQUE, Adres varchar(255) NOT NULL, WartoscRabatu float NOT NULL, LicznikAktywnychRezerwacji int(10) NOT NULL, PRIMARY KEY (IdKonsumenta, OsobaID));
CREATE TABLE KlientNiezalogowany (ID int(10) NOT NULL AUTO_INCREMENT, IP varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Pojazdy (ID int(10) NOT NULL AUTO_INCREMENT, CennikID int(10) NOT NULL, FiliaID int(10) NOT NULL, KategoriaID int(10) NOT NULL, KonsumentOsobaID int(10) NOT NULL, KonsumentIdKonsumenta int(10) NOT NULL, KlientNiezalogowanyID int(10) NOT NULL, Rocznik int(10) NOT NULL, Pojemnosc double NOT NULL, Moc double NOT NULL, Przebieg int(10) NOT NULL, NrRejestracyjny varchar(255) NOT NULL, DataPrzegladu date NOT NULL, DataUbezpieczeniaOC date NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Rezerwacja (Id int(10) NOT NULL AUTO_INCREMENT, DataPoczatek date NOT NULL, DataKoniec date NOT NULL, KwotaCalkowita double NOT NULL, CzyAktywne tinyint(1) NOT NULL, KonsumentIdKonsumenta int(10) NOT NULL, KonsumentOsobaID int(10) NOT NULL, CzyAnulowanoRezerwacje tinyint(1) NOT NULL, PojazdyID int(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Usługi (Id int(10) NOT NULL AUTO_INCREMENT, Nazwa varchar(255) NOT NULL UNIQUE, CenaNetto double NOT NULL, CenaBrutto double NOT NULL, Opis varchar(255), Kategorie_uslugid int(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Platnosc (ID int(10) NOT NULL AUTO_INCREMENT, Data date NOT NULL, Kwota double NOT NULL, Forma int(10) NOT NULL, Status int(10) NOT NULL, RezerwacjaId int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Marka (ID int(10) NOT NULL AUTO_INCREMENT, Nazwa varchar(255), PRIMARY KEY (ID));
CREATE TABLE Model (ID int(10) NOT NULL AUTO_INCREMENT, MarkaID int(10) NOT NULL, Nazwa varchar(255) NOT NULL, Ilosc_miejsc int(10) NOT NULL, Ilosc_drzwi int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE `Rodzaj nadwozia` (ID int(10) NOT NULL AUTO_INCREMENT, Nazwa varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Role (ID int(10) NOT NULL AUTO_INCREMENT, Nazwa varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Uprawnienia (ID int(10) NOT NULL AUTO_INCREMENT, Nazwa varchar(255) NOT NULL, KodUprawnienia varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Kategoria (ID int(10) NOT NULL AUTO_INCREMENT, Nazwa varchar(255) NOT NULL, Opis varchar(255), PRIMARY KEY (ID));
CREATE TABLE Filia (ID int(10) NOT NULL AUTO_INCREMENT, NazwaFilii varchar(255) NOT NULL, Adres varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Cennik (ID int(10) NOT NULL AUTO_INCREMENT, CenaWypozyczeniaZaDzien double NOT NULL, CenaWypozyczeniaZaTydzien double NOT NULL, CenaWypozyczeniaZaMiesiac double NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Role_Uprawnienia (RoleID int(10) NOT NULL, UprawnieniaID int(10) NOT NULL, PRIMARY KEY (RoleID, UprawnieniaID));
CREATE TABLE `Model_Rodzaj nadwozia` (ModelID int(10) NOT NULL, `Rodzaj nadwoziaID` int(10) NOT NULL, PRIMARY KEY (ModelID, `Rodzaj nadwoziaID`));
CREATE TABLE Kategoria_Marka (KategoriaID int(10) NOT NULL, MarkaID int(10) NOT NULL, PRIMARY KEY (KategoriaID, MarkaID));
CREATE TABLE Usługi_listaPojazdow (UsługiId int(10) NOT NULL, UsługiIndex int(10) NOT NULL, ListaPojazdow int(10), PRIMARY KEY (UsługiId, UsługiIndex));
CREATE TABLE Lista_pojazdow (UsługiId int(10) NOT NULL, PojazdyID int(10) NOT NULL, PRIMARY KEY (UsługiId, PojazdyID));
CREATE TABLE Lista_uslug (RezerwacjaId int(10) NOT NULL, UsługiId int(10) NOT NULL, PRIMARY KEY (RezerwacjaId, UsługiId));
CREATE TABLE Kategorie_uslug (id int(10) NOT NULL AUTO_INCREMENT, opis int(255), PRIMARY KEY (id));
ALTER TABLE Konsument ADD CONSTRAINT FKKonsument951416 FOREIGN KEY (OsobaID) REFERENCES Osoba (ID);
ALTER TABLE Pojazdy ADD CONSTRAINT FKPojazdy996894 FOREIGN KEY (KlientNiezalogowanyID) REFERENCES KlientNiezalogowany (ID);
ALTER TABLE Pojazdy ADD CONSTRAINT FKPojazdy346277 FOREIGN KEY (KonsumentIdKonsumenta, KonsumentOsobaID) REFERENCES Konsument (IdKonsumenta, OsobaID);
ALTER TABLE Rezerwacja ADD CONSTRAINT FKRezerwacja785030 FOREIGN KEY (KonsumentIdKonsumenta, KonsumentOsobaID) REFERENCES Konsument (IdKonsumenta, OsobaID);
ALTER TABLE Osoba ADD CONSTRAINT FKOsoba501782 FOREIGN KEY (RoleID) REFERENCES Role (ID);
ALTER TABLE Role_Uprawnienia ADD CONSTRAINT FKRole_Upraw533248 FOREIGN KEY (RoleID) REFERENCES Role (ID);
ALTER TABLE Role_Uprawnienia ADD CONSTRAINT FKRole_Upraw776668 FOREIGN KEY (UprawnieniaID) REFERENCES Uprawnienia (ID);
ALTER TABLE Platnosc ADD CONSTRAINT FKPlatnosc628672 FOREIGN KEY (RezerwacjaId) REFERENCES Rezerwacja (Id);
ALTER TABLE Pojazdy ADD CONSTRAINT FKPojazdy167884 FOREIGN KEY (KategoriaID) REFERENCES Kategoria (ID);
ALTER TABLE Pojazdy ADD CONSTRAINT FKPojazdy248719 FOREIGN KEY (FiliaID) REFERENCES Filia (ID);
ALTER TABLE Pojazdy ADD CONSTRAINT FKPojazdy768473 FOREIGN KEY (CennikID) REFERENCES Cennik (ID);
ALTER TABLE `Model_Rodzaj nadwozia` ADD CONSTRAINT FKModel_Rodz353380 FOREIGN KEY (ModelID) REFERENCES Model (ID);
ALTER TABLE `Model_Rodzaj nadwozia` ADD CONSTRAINT FKModel_Rodz175200 FOREIGN KEY (`Rodzaj nadwoziaID`) REFERENCES `Rodzaj nadwozia` (ID);
ALTER TABLE Model ADD CONSTRAINT FKModel436611 FOREIGN KEY (MarkaID) REFERENCES Marka (ID);
ALTER TABLE Kategoria_Marka ADD CONSTRAINT FKKategoria_657976 FOREIGN KEY (KategoriaID) REFERENCES Kategoria (ID);
ALTER TABLE Kategoria_Marka ADD CONSTRAINT FKKategoria_872960 FOREIGN KEY (MarkaID) REFERENCES Marka (ID);
ALTER TABLE Usługi_listaPojazdow ADD CONSTRAINT FKUsługi_lis864733 FOREIGN KEY (UsługiId) REFERENCES Usługi (Id);
ALTER TABLE Lista_pojazdow ADD CONSTRAINT FKLista_poja107147 FOREIGN KEY (UsługiId) REFERENCES Usługi (Id);
ALTER TABLE Lista_pojazdow ADD CONSTRAINT FKLista_poja627635 FOREIGN KEY (PojazdyID) REFERENCES Pojazdy (ID);
ALTER TABLE Rezerwacja ADD CONSTRAINT FKRezerwacja632339 FOREIGN KEY (PojazdyID) REFERENCES Pojazdy (ID);
ALTER TABLE Lista_uslug ADD CONSTRAINT FKLista_uslu943702 FOREIGN KEY (RezerwacjaId) REFERENCES Rezerwacja (Id);
ALTER TABLE Lista_uslug ADD CONSTRAINT FKLista_uslu830087 FOREIGN KEY (UsługiId) REFERENCES Usługi (Id);
ALTER TABLE Usługi ADD CONSTRAINT FKUsługi183755 FOREIGN KEY (Kategorie_uslugid) REFERENCES Kategorie_uslug (id);
